TrajectoryPlannerROS: # determines the speeds sent to robot when navigating
  max_vel_x: 0.3 #0.45
  min_vel_x: -0.3
  max_vel_theta: 1.0
  min_in_place_vel_theta: -0.4

  acc_lim_theta: 3.0 #3.2
  acc_lim_x: 0.7 #2.5
  acc_lim_y: 0.7 #2.5

  occdist_scale: 0.01

  holonomic_robot: true # the final robot might be true
