robot_base_frame: base_link

footprint: [[-0.2, -0.1], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.1]] # sets the bounds of the simulation robot
# footprint: [[-0.35, -0.2075], [-0.35, 0.2075], [0.35, 0.2075], [0.35, -0.2075]] # bounds for jiqi
footprint_padding: 0.05
robot_radius: 0.3

map_type: costmap

transform_tolerance: 1.5 # max time (s) to wait for transforms to become available between frames
obstacle_range: 2.5
raytrace_range: 3.0

static_layer:
  map_topic: map
  subscribe_to_updates: true
  lethal_cost_threshold: 100

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}
  # inf_is_valid: true

inflater_layer:

  inflation_radius: 0.1 # max distance from a obstacle that can affect the path plan through incurred cost
  cost_scaling_factor: 10.0