# obstacle_range: 2.5 # determines the max range (m) that an obstacle will be detected in the costmapP
# raytrace_range: 3.0 # determines the max range (m) the sensor will raytrace/map around it

# footprint: [[-0.2, -0.1], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.1]] # sets the bounds of the robot
# #robot_radius: 0.5 # sets the radius of robot
# #inflation_radius: 0.55
# #footprint_padding: 0.55 # adds extra padding to robot that only appears on the costmap

# observation_sources: laser_scan_sensor 
# # sets the sensors that should be listened to e.g. point_cloud_sensor

# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#static_layer:
 #   map_topic: /map
  #  subscribe_to_updates: true
   # static_map: true
# sets where the static map will be published from and with also listen to updates of the map  

#obstacles_layer:
 #   observation_sources: scan
  #  scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 8.5}

##

global_frame: map
robot_base_frame: base_link

footprint: [[-0.2, -0.1], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.1]] # sets the bounds of the robot
footprint_padding: 0.1