global_costmap:
  update_frequency: 15.0 # the rate the costmap updates
  static_map: true # if the robot is localising in an existing map set to true
  rolling_window: false # sets whether the robot will always be centered on the map
  width: 50
  height: 50
  resolution: 0.05
  static_layer:
    map_topic: /map
    subscribe_to_updates: true
    lethal_cost_threshold: 60
  inflater_layer:
    inflation_radius: 0.1
    cost_scaling_factor: 0.5

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}