global_costmap:

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0 # the rate the costmap updates
  publish_frequency: 2.0 # the rate in Hz that visual data is published
  static_map: false # if the robot is localising in an existing map set to true
  rolling_window: false # sets whether the robot will always be centered on the map
  width: 20.0
  height: 20.0
  resolution: 0.05

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}