global_frame: map # local costmap of is based on map and pose data stored within odom frame. Allows for smooth transistion of local costmap. Obstacle will not be blurred
robot_base_frame: base_link
update_frequency: 10.0 # the rate in Hz that the costmap updates
publish_frequency: 2.0 # the rate in Hz that visual data is published
static_map: false # if the robot is localising in an existing map set to true
rolling_window: true # determines if the costmap is always centered around robot when it moves
width: 5.0 # sets the width of the local costamp
height: 5.0 # sets the height of the local costmap
resolution: 0.05


plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  