local_costmap:
  update_frequency: 10.0 # the rate in Hz that the costmap updates
  publish_frequency: 5.0 # the rate in Hz that visual data is published
  static_map: false # is the robot is localising in an existing map set to true
  rolling_window: true # determines if the costmap is always centered around robot when it moves
  width: 5.0 # sets the width of the local costamp
  height: 5.0 # sets the height of the local costmap
  resolution: 0.05

  inflater_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 0.2


  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    max_obstacle_height: 3
    obstacle_range: 10
    raytrace_range: 11

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  # - {name: obstacles_layer, type: "costmap_2d::VoxelLayer"}