# Max range (in metres) sensor reading resulting in obstacle being put/updated in costmap
obstacle_range: 2.5
# Max range (in metres) freespace will be raytraced
raytrace_range: 3.0
# Set footprint of motor (centre assumed to be at (0.0, 0.0))
footprint: [[-0.35, -0.2075], [-0.35, 0.2075], [0.35, 0.2075], [0.35, -0.2075]]
# Max distance (in metres) from obstacle that cost will be incurred
inflation_radius: 0.55

# Defines sensors passing information to the costmap (LiDAR, ZED Camera?)
observation_sources: laser_scan_sensor point_cloud_sensor

# Costmap Layers

static_layer:
  map_topic: map
  subscribe_to_updates: true
  lethal_cost_threshold: 100

obstacle_layer:
  observation_sources: laser_scan_sensor #, point_cloud_sensor
  laser_scan_sensor:
    sensor_frame: laser # Sensor coordinate frame name
    data_type: LaserScan # Set to LaserScan or PointCloud dependent on topic message type
    topic: scan # Topic name sensor publishes data on
    marking: true # Will sensor add obstacle information to the costmap
    clearing: true # Will sensor clear obstacle information from the costmap
  # point_cloud_sensor:
  #   sensor_frame: zedCamera
  #   data_type: PointCloud
  #   topic: point_cloud
  #   marking: true
  #   clearing: true
  # inf_is_valid: true

inflater_layer:
  inflation_radius: 0.1 # max distance from a obstacle that can affect the path plan through incurred cost
  cost_scaling_factor: 10.0