# Max range (in metres) sensor reading resulting in obstacle being put/updated in costmap
obstacle_range: 2.5
# Max range (in metres) freespace will be raytraced
raytrace_range: 3.0
# Set footprint of motor (centre assumed to be at (0.0, 0.0))
footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
# Max distance (in metres) from obstacle that cost will be incurred
inflation_radius: 0.55

# Defines sensors passing information to the costmap (LiDAR, ZED Camera?)
observation_sources: laser_scan_sensor point_cloud_sensor

# Set sensor parameters
laser_scan_sensor:
{
  sensor_frame: frame_name, # Sensor coordinate frame name
  data_type: LaserScan, # Set to LaserScan or PointCloud dependent on topic message type
  topic: scan, # Topic name sensor publishes data on
  marking: true, # Will sensor add obstacle information to the costmap
  clearing: true # Will sensor clear obstacle information from the costmap
}

point_cloud_sensor:
{
  sensor_frame: frame_name,
  data_type: PointCloud,
  topic: topic_name,
  marking: true,
  clearing: true
}