# Defines which coordinate frame should the costmap run in
global_frame: map
# Defines the coordinate frame referenced for robot base
robot_base_frame: base_link
# Define costmap update loop frequency (in Hz)
update_frequency: 15.0
# Determines whether costmap should initialise based on map served by map_server (true) or not (false)
static_map: true
# Determines whether costmap remains centered on the robot during movement (true) or not (false)
rolling_window: true

plugins:
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}