#
base_global_planner: global_planner/GlobalPlanner
planner_frequency: 1.0
planner_patience: 5.0

#
base_local_planner: teb_local_planer/TebLocalPlannerROS
controller_frequency: 5.0
controller_patience: 15.0